train_transform:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: transforms.transforms.ResizeWithPadding
      max_size: 600
      aspect_ratio: 1.6
      fill_value: 0
      padding_mode: "constant"
    - _target_: torchvision.transforms.RandomHorizontalFlip
      p: 0.5
    - _target_: torchvision.transforms.ConvertImageDtype
      dtype:
        _target_: transforms.transforms.get_dtype

# in test we skip RandomHorizontalFlip
test_transform:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: transforms.transforms.ResizeWithPadding
      max_size: 600
      aspect_ratio: 1.6
      fill_value: 0
      padding_mode: "constant"
    - _target_: torchvision.transforms.ConvertImageDtype
      dtype:
        _target_: transforms.transforms.get_dtype
