hydra:
  run:
    dir: .
  output_subdir: null

defaults:
  - optimizer: adam
  - model: mobilenetv3_small
  - scheduler: multistep
  - loss: nll_loss
  - transforms: transform
  - _self_

exp_dir: ./exp/pneumonia_cls

datamodule:
  _target_: training.dataloader.ChestXrayDataModule
  data_dir: ./data/images/chest_xray
  train_batch_size: 64
  test_batch_size: 128
  val_batch_size: 128
  train_load_workers: 2
  test_load_workers: 2
  val_load_workers: 2
  class_mapping:
    PNEUMONIA: 1
    NORMAL: 0

model_trainer:
  _target_: training.trainer.PneumoniaClsTrainer
  optimizer_config: ${optimizer}
  loss_module: ${loss}
  class_labels: ['NORMAL', 'PNEUMONIA']
  scheduler_config: ${scheduler}
  unfreeze_after_epoch: 5

trainer:
  _target_: pytorch_lightning.trainer.trainer.Trainer
  amp_backend: 'native'
  benchmark: true
  gpus: 1
  deterministic: false
  log_every_n_steps: 50
  precision: 16
  max_epochs: 10
  fast_dev_run: false
  check_val_every_n_epoch: 2
  default_root_dir: ${exp_dir}
  logger:
    _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
    save_dir: ${exp_dir}/logs
  callbacks:
    - _target_: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      dirpath: ${exp_dir}/checkpoint
      save_last: true
      save_top_k: 2
      mode: 'max'
      every_n_epochs: 3
      monitor: Valid/AUC_ROC

