name: Test main code

on:
  push:
    branches: [master, develop]
    paths:
      - '**.py'
      - 'configs/**'
      - log_settings.yaml
      - requirements*.txt
  pull_request:
    branches: [master, develop]
    paths:
      - '**.py'
      - 'configs/**'
      - log_settings.yaml
      - requirements*.txt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip dependecies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements.dev.txt


      - name: Test with pytest
        run: pytest --cov=model --cov=training ./tests