name: CML autoreport

on:
  pull_request:
    branches: [master, develop, feature/training]
    paths:
      - dvc.yaml
      - dvc.lock
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          pip install -r ./requirements.dev.txt -r ./requirements.txt

      - name: Prepare DVC cache
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.DVC_DATA_SECRET }}
        run: |
          cat << EOF > ./.dvc/config.local
          ['remote "storage"']
            gdrive_service_account_json_file_path = ${{ github.workspace }}/.dvc/tmp/gdrive-user-credentials.json
          EOF

          dvc pull save-conf-matrix test train

      - name: Send CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc metrics show ./exp/pneumonia_cls/test_metrics/auc.json >> report.md
          dvc repro -s save-conf-matrix
          cml-publish ./matrix.jpg --md --title 'Confusion matrix' >> report.md
          cml-send-comment report.md
